# Generated by Django 5.1.6 on 2025-03-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='extracted_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
