# Generated by Django 5.1.6 on 2025-03-20 18:55

import archivos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0004_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=archivos.models.user_directory_path),
        ),
    ]
