services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./myproject:/app
      - ./myproject/media:/app/media
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=myproject.settings
    networks:
      - app-network
    env_file:
      - myproject/.env

  frontend:
    build:
      context: ./myproject/frontend 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8000
    networks:
      - app-network
    env_file:
      - myproject/.env

networks:
  app-network:
    driver: bridge
