version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./myproject:/app
      - ./media:/app/media
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=myproject.settings
    command: >
      bash -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./myproject/frontend 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
